### ISSUE TITLE
`weights` parameter is not used to calculate observed population size

### ISSUE THREAD

**Issue by BERENZ** [ncn-foreigners/singleRcapture#24]
Imagine we have an aggregated dataset where each row corresponds to two observations in the whole dataset. This is denoted by `rep.int(2, nrow(farmsubmission))`

```r
ModelPo <- estimate_popsize(formula = TOTAL_SUB ~ .,
                            data = farmsubmission,
                            pop.var = "analytic",
                            model = "ztpoisson",
                            method = "mle", 
                            weights = rep.int(2, nrow(farmsubmission)))
```

so the observed population should be `sum(nrow(farmsubmission)* weights) = 24072`   but it is not included included in the output

```
Observed proportion: 65.6% (N obs = 12036)
```

**Comment by Kertoo** [comment]
Added to **0.3.0** roadmap.
