### ISSUE TITLE
Complete documentation.

### ISSUE THREAD

**Issue by BERENZ** [ncn-foreigners/singleRcapture#40]

**Comment by BERENZ** [comment]
Please state what should be added and where. I can read the documentation and fill blanks were possible.

**Comment by Kertoo** [comment]
The pseudohurdle models are not yet described in `/man/singleRmodels.Rd` and chao and zelterman models could have more polished documentation.

Data files exported in the package can have better documentation as well.

Maybe some math on how `vcovHC` works.

If I can remember more I'll edit this comment

**Comment by Kertoo** [comment]
After #43 I think only updating documentation for .Rdata files exported in the package requires improments since we will wait with describing pseudohurdle models for the paper on them to published.

**Comment by Kertoo** [comment]
I think we can close this after 3fe588e.

**Comment by Kertoo** [comment]
Closing after CRAN submission.
